import type { EstimateTableRow } from '@/types/estimate';

// 初期テンプレートのJSONデータ
export const initialTemplateData = {
  id: 'degasser_1800',
  name: '脱気器 1800',
  description: '脱気器 1800 のテンプレート',
  data: [
    {
      type: '材料(03)',
      item: '胴体',
      code: '0103001',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '外圧ﾘﾝｸﾞ',
      code: '0103002',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '鏡板',
      code: '0103003',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '支持脚',
      code: '0103004',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '支持脚当板',
      code: '0103005',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '丸型ﾏﾝﾎｰﾙ',
      code: '0103006',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: 'ﾏﾝﾎｰﾙ補強板',
      code: '0103007',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '丸型ﾏﾝﾎｰﾙ',
      code: '0103008',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: 'ﾏﾝﾎｰﾙ補強板',
      code: '0103009',
      inputType: '入力No.',
      detail: 'SM400B',
      spec: '',
      strength: '400N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '丸型ﾏﾝﾎｰﾙﾋﾝｼﾞ',
      code: '0103010',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '丸型ﾏﾝﾎｰﾙﾋﾝｼﾞ',
      code: '0103011',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '脱気器水室',
      code: '0103012',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: '水室ｶﾊﾞｰ',
      code: '0103013',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(03)',
      item: 'ﾄﾚｲ枠',
      code: '0103014',
      inputType: '入力No.',
      detail: '',
      spec: '',
      strength: '',
      category: '材料(03)',
      result: '',
      value1: '',
      value2: '',
      value3: '',
      auto: false,
    },
    {
      type: '材料(03)',
      item: '緩衝板',
      code: '0103015',
      inputType: '入力No.',
      detail: 'SUS304',
      spec: '',
      strength: '520N/mm²',
      category: '材料(03)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(04)',
      item: 'ﾉｽﾞﾙ',
      code: '0104016',
      inputType: '入力No.',
      detail: 'STPG370',
      spec: '',
      strength: '370N/mm²',
      category: '材料(04)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(07)',
      item: 'ﾏﾝﾎｰﾙﾌﾗﾝｼﾞ',
      code: '0107017',
      inputType: '入力No.',
      detail: 'SS400/C.S.',
      spec: '',
      strength: '245N/mm²',
      category: '材料(07)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(07)',
      item: 'ﾏﾝﾎｰﾙﾌﾗﾝｼﾞ',
      code: '0107018',
      inputType: '入力No.',
      detail: 'SS400/C.S.',
      spec: '',
      strength: '245N/mm²',
      category: '材料(07)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(07)',
      item: 'ﾉｽﾞﾙﾌﾗﾝｼﾞ',
      code: '0107019',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(07)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(08)',
      item: 'ﾊﾟｯｷﾝ･ｶﾞｽｹｯﾄ',
      code: '0108020',
      inputType: '入力No.',
      detail: '',
      spec: '',
      strength: '',
      category: '材料(08)',
      result: '',
      value1: '',
      value2: '',
      value3: '',
      auto: false,
    },
    {
      type: '材料(08)',
      item: 'ｽﾌﾟﾚｰﾉｽﾞﾙ･座',
      code: '0108021',
      inputType: '入力No.',
      detail: 'SS400',
      spec: '',
      strength: '245N/mm²',
      category: '材料(08)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(10)',
      item: 'ｽﾌﾟﾚｰﾉｽﾞﾙ',
      code: '0110022',
      inputType: '入力No.',
      detail: 'SCS13/SUS304',
      spec: '',
      strength: '520N/mm²',
      category: '材料(10)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(10)',
      item: 'ｽﾌﾟﾚｰﾉｽﾞﾙﾊﾟｯｷﾝ',
      code: '0110023',
      inputType: '入力No.',
      detail: 'SUS304',
      spec: '',
      strength: '520N/mm²',
      category: '材料(10)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(08)',
      item: 'ﾄﾚｲ',
      code: '0108024',
      inputType: '入力No.',
      detail: 'SUS304',
      spec: '',
      strength: '520N/mm²',
      category: '材料(08)',
      result: '適合',
      value1: '',
      value2: '',
      value3: '',
      auto: true,
    },
    {
      type: '材料(08)',
      item: '銘称板･購入品等',
      code: '0108025',
      inputType: '入力No.',
      detail: '',
      spec: '',
      strength: '',
      category: '材料(08)',
      result: '',
      value1: '',
      value2: '',
      value3: '',
      auto: false,
    },
  ],
};

// JSONデータをEstimateTableRow形式に変換する関数
export function convertTemplateDataToTableRows(
  data: typeof initialTemplateData.data
): EstimateTableRow[] {
  return data.map((item, index) => ({
    id: crypto.randomUUID(),
    modelNumber: item.code || '',
    name: item.item || '',
    partType: item.type || item.category || '',
    material: item.detail || '',
    dimensions: {
      partType: item.type || item.category || '',
      spec: item.spec || '',
      strength: item.strength || '',
      category: item.category || '',
      result: item.result || '',
      value1: item.value1 || '',
      value2: item.value2 || '',
      value3: item.value3 || '',
    },
    quantity: 1,
    weight: 0,
    unitPrice: 0,
    price: 0,
    autoDisplay: false,
    isAuto: item.auto || false,
    isAutoInput: item.auto || false,
    isTemplateDiff: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }));
}

// 初期テンプレートをEstimateTableRow形式に変換
export function getInitialTemplateTableRows(): EstimateTableRow[] {
  return convertTemplateDataToTableRows(initialTemplateData.data);
}

